apiVersion: v1
kind: Pod
metadata:
  name: openethereum
  labels:
    app: ethereum
spec:
  containers:
  - name: openethereum-container
    image: openethereum/openethereum:v3.1.0
    ports:
    - containerPort: 8545
    command: ['/home/openethereum/openethereum']
    args: ['--jsonrpc-interface=0.0.0.0','--author=0xf34fa87db39d15471bebe997860dcd49fc259318', '--no-warp']
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum
spec:
  selector:
    app: ethereum
  ports:
  - port: 8545