apiVersion: v1
kind: Pod
metadata:
  name: open-overline-pool-frontend
  labels:
    app: open-overline-pool
spec:
  volumes:
  - name: ssh-secret
    secret:
      secretName: secret-ssh-auth
  containers:
    - name: oovp-test-container
      image: lgray/open-overline-pool-frontend:latest
      env:
      - name: TZ
        value: "Etc/Universal"
      args: ['server', '--host', '0.0.0.0', '--port', '8080', '-dev']
      ports:
      - containerPort: 8080 # http
      - containerPort: 7020 # live reload
      imagePullPolicy: Always