apiVersion: v1
kind: Pod
metadata:
  name: open-overline-pool-payouts
  labels:
    app: open-overline-pool
spec:
  volumes:
  - name: config
    secret:
      secretName: payouts-config-file  
  containers:
  - name: oovp-test-container
    image: lgray/open-overline-pool-api:latest
    env:
    - name: PRIVATE_KEY_SECRET
      valueFrom:
        secretKeyRef:
          name: pool-miner-private-key
    volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
    args: ['/config/config.payouts.json']
    imagePullPolicy: Always