apiVersion: v1
kind: Service
metadata:
  name: open-overline-pool-frontend
spec:
  ports:
  - name: web
    port: 80
  - name: livereload
    port: 7020
  selector:
    app: open-overline-pool-frontend
  externalIPs:
  - 157.245.116.220
---
apiVersion: v1
kind: Service
metadata:
  name: open-overline-pool-api
spec:
  ports:
  - name: api
    port: 6283
  selector:
    app: open-overline-pool-api
  externalIPs:
  - 157.245.116.220
---
apiVersion: v1
kind: Service
metadata:
  name: open-overline-pool-proxy
spec:
  ports:
  - name: stratum-mining
    port: 3141
  - name: http-mining
    port: 3142
  selector:
    app: open-overline-pool-proxy
  externalIPs:
  - 157.245.116.220
