apiVersion: v1
kind: Pod
metadata:
  name: open-overline-pool-unlocker
  labels:
    app: open-overline-pool
spec:
  volumes:
  - name: config
    secret:
      secretName: unlocker-config-file
  containers:
  - name: oovp-test-container
    image: lgray/open-overline-pool-api:latest
    env:
    - name: POOL_FEE_KEY
      valueFrom:
        secretKeyRef:
          name: pool-fee-key
          key: value
    - name: POOL_NODE_SCOOKIE
      valueFrom:
        secretKeyRef:
          name: pool-miner-scookie
          key: value
    volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
    args: ['/config/config.unlocker.json']
    imagePullPolicy: Always