apiVersion: v1
kind: Pod
metadata:
  name: open-overline-pool-unlocker
  labels:
    app: open-overline-pool
spec:
  volumes:
  - name: config
    secret:
      secretName: unlocker-config-file
  containers:
  - name: oovp-test-container
    image: lgray/open-overline-pool-api:latest
    volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
    args: ['/config/config.unlocker.json']
    imagePullPolicy: Always