kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol-bcnode-db
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol-bcnode-db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-bcnode-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: vol-bcnode-db
  resources:
    requests:
      storage: 50Gi
