apiVersion: v1
kind: Service
metadata:
  name: bcnode-svc
spec:
  selector:
    app: bcnode
  ports:
    - name: bccomms
      protocol: TCP
      port: 16060
      targetPort: 16060
    - name: bcbootstrap
      protocol: TCP
      port: 16061
      targetPort: 16061
    - name: rpc
      protocol: TCP
      port: 3000
      targetPort: 3000
