name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
  # Run daily at 0:01 UTC
  schedule:
    - cron:  '1 0 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: build olminer (ubuntu-latest)

    steps:
    - uses: actions/checkout@master
      with:
        submodules: True
    - name: zip repo
      run: |
        cd ../
        tar -cvzf open-overline-pool.tar.gz open-overline-pool/
        mv open-overline-pool.tar.gz open-overline-pool/docker/
        cd open-overline-pool
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build bcnode image
      uses: docker/build-push-action@v2
      with:
        context: docker/
        file: docker/Dockerfile.bcnode
        tags: local/bcnode:latest
    - name: Build api server image
      uses: docker/build-push-action@v2
      with:
        context: docker/
        file: docker/Dockerfile.api
        tags: local/open-overline-pool-api:latest
    - name: Build frontend image
      uses: docker/build-push-action@v2
      with:
        context: docker/
        file: docker/Dockerfile.frontend
        tags: local/open-overline-pool-frontend:latest
    - name: Build grpc reformatter image
      uses: docker/build-push-action@v2
      with:
        context: docker/
        file: docker/Dockerfile.reformatter
        tags: local/open-overline-pool-reformatter:latest